### PR TITLE
Added variable documentation in defaults

### PR DESCRIPTION
**Pull request by khappone**
Documented the use of variables in default/main.yml. Added package
exlclude variable for explicit package excluding during installation.

Fixed root SSH key addition logic in kickstart template.

### CODE REVIEW

**Comment by rlaurika** [comment]
@khappone Any thoughts on also defining a base_packages variable that would contain the packages that are now hardcoded to be installed every time? E.g. `@core`, `vim`, `tcpdump`, `lvm2` etc.

This would allow users to not install packages they don't need.

**Comment by khappone** [comment]
Honestly, it seems like a reasonable idea. I think @core should always be there though. The only reason I didn't implement it so far was laziness, I had already done the push before I read that part of the comment :). I'll fix it.

**Comment by rlaurika** [comment]
Yes, I think `@core` is mandatory. It might have also been so that you could replace `@core` with `@Base` and still get the same packages.

**Comment by khappone** [comment]
Ok. Fixed now, and tested that a deploy works.

**Comment by rlaurika** [comment]
Looks good to me. I'll merge.

**Pull request merged**
